#Default port is 8080
server:
  port: 8080
  
spring:
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
#Resolution TimeOut(1)    
#(1)    leaseExpirationDurationInSeconds: 30 
#(1)    leaseRenewalIntervalInSeconds: 10
#(1)    statusPageUrlPath: ${management.contextPath}/info      
#(1)    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#(1)   healthcheck:
#(1)      enabled: true  
        
#management:
#  contextPath: /admin     
     
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG      